In [7]:
import numpy as np 
import pandas as  pd

from sklearn.model_selection import train_test_split

from sklearn.impute  import KNNImputer, SimpleImputer 
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [8]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [9]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [10]:
df.isnull().sum()*100

Age         17700
Pclass          0
Fare            0
Survived        0
dtype: int64

In [11]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [15]:
X_train.sample(5)

      Age  Pclass      Fare
454   NaN       3    8.0500
651  18.0       2   23.0000
318  31.0       1  164.8667
315  26.0       3    7.8542
560   NaN       3    7.7500

In [17]:
knn = KNNImputer(n_neighbors=5,weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [20]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)
y_pred = lr.predict(X_test_trf)
accuracy_score(y_test, y_pred)

0.7374301675977654

In [25]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [27]:
lr = LogisticRegression()

lr.fit(X_train_trf2, y_train)
y_pred2 = lr.predict(X_test_trf2)
accuracy_score(y_test, y_pred2)

0.7374301675977654